/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2omeros;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;


/**
 * This class is the interface that helps the user to log in to his account
 * @author GeorgeKirm
 * @author GT
 */
public class GUIforLogIn_Register extends javax.swing.JFrame {
 

    /**
     * Creates new form GUIforLogIn
     */
    public GUIforLogIn_Register(char a) {
        initComponents();
        getContentPane().repaint();
        if ( a == 'l'){ //ama o xristis delei na kanei log in aferounte ta koumpia pou xriazonte mono gia to register
            jPanel1.remove(passwordT1);
            jPanel1.remove(password2);
            jPanel1.remove(AdmRadio);
            jPanel1.remove(UsRadio);
            //jPanel1.remove(jPanel2);
            jPanel1.remove(UorAlabel);
            jPanel1.revalidate();
            jPanel1.repaint();
            remove(jPanel2); 
            resize(320, 320);
            repaint();
            log_RegB.setText("Log In"); //allazei kai to text merikwn koumpiwn
            passwordT.setEchoChar((char) 0);
            welcomeText.setText("Please log in to your account to continue:");
        }else{ // ama thelei na kanei register tote allazoun aplos merika text
            log_RegB.setText("Register");
            welcomeText.setText("Please complete all fields to Register:");
            UsRadio.doClick(); //clickarete os proth epilogi na kaneis register os aplos xristis
            jPanel2.setVisible(false); //efoson exei patithei h epilogh na ginei register os aplos xristis to jpanel2 den emfanizete
            passwordT.setEchoChar((char) 0); //afth h entolh kanei ta password fields na fenonte me alfabito kai oxi ***
            passwordT1.setEchoChar((char) 0);
            adpassword.setEchoChar((char) 0);
        }
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        password1 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        userName1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        welcomeText = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        userNameT = new javax.swing.JTextField();
        passwordT = new javax.swing.JPasswordField();
        password = new javax.swing.JLabel();
        password2 = new javax.swing.JLabel();
        passwordT1 = new javax.swing.JPasswordField();
        fieldsText = new javax.swing.JLabel();
        UorAlabel = new javax.swing.JLabel();
        AdmRadio = new javax.swing.JRadioButton();
        UsRadio = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        userName2 = new javax.swing.JLabel();
        userName3 = new javax.swing.JLabel();
        adusername = new javax.swing.JTextField();
        adpassword = new javax.swing.JPasswordField();
        fieldsText1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cancelT = new javax.swing.JButton();
        log_RegB = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        quitB = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        password1.setText("Password:");

        jMenuItem1.setText("jMenuItem1");

        userName1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userName1.setText("Username:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(340, 296));

        welcomeText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcomeText.setText("#######");

        userName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userName.setText("Username:");

        userNameT.setText("Enter your username.");
        userNameT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameTFocusLost(evt);
            }
        });

        passwordT.setText("Enter your password.");
        passwordT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTFocusLost(evt);
            }
        });

        password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        password.setText("Password:");

        password2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        password2.setText("Verify Password:");
        password2.setOpaque(true);

        passwordT1.setText("Enter your password.");
        passwordT1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordT1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordT1FocusLost(evt);
            }
        });

        fieldsText.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        fieldsText.setForeground(new java.awt.Color(255, 0, 0));
        fieldsText.setText("*All Fields are neccessary.");

        UorAlabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        UorAlabel.setText("Register as:");

        AdmRadio.setText("Administrator");
        AdmRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmRadioActionPerformed(evt);
            }
        });

        UsRadio.setText("User");
        ButtonGroup group = new ButtonGroup();
        group.add(AdmRadio);
        group.add(UsRadio);
        UsRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(welcomeText))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(password2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(passwordT1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(password)
                                        .addComponent(userName))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(userNameT)
                                        .addComponent(passwordT, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(fieldsText)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(UorAlabel)
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsRadio)
                            .addComponent(AdmRadio))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(welcomeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldsText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password)
                    .addComponent(passwordT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdmRadio)
                    .addComponent(UorAlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsRadio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        userName2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userName2.setText("Administrator's Username:");

        userName3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userName3.setText("Administrator's password:");

        adusername.setText("Enter admins username.");
        adusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                adusernameFocusLost(evt);
            }
        });

        adpassword.setText("Enter admins password.");
        adpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                adpasswordFocusLost(evt);
            }
        });

        fieldsText1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldsText1.setForeground(new java.awt.Color(255, 0, 0));
        fieldsText1.setText("The following fields must be entered by administrator");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userName2)
                            .addComponent(userName3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adusername, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(adpassword)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(fieldsText1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldsText1)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userName2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userName3)
                    .addComponent(adpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        cancelT.setText("Cancel");
        cancelT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelTActionPerformed(evt);
            }
        });

        log_RegB.setText("Log In");
        log_RegB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_RegBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(log_RegB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(log_RegB)
                    .addComponent(cancelT))
                .addGap(10, 10, 10))
        );

        File.setText("File");

        quitB.setText("Quit");
        quitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBActionPerformed(evt);
            }
        });
        File.add(quitB);

        jMenuBar1.add(File);

        jMenu2.setText("Help");

        jMenuItem2.setText("Help");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void log_RegBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_RegBActionPerformed
        Users temp = new Users();
        if(userNameT.getText().contains(" ")||passwordT.getText().contains(" ")){ //den theloume space sta fields giati me space xorizonte oi metablites sto userMap.
            JOptionPane.showMessageDialog(null, "Please don't put space in the fields.", 
                    "Error message", JOptionPane.PLAIN_MESSAGE);
        }else{
            if(log_RegB.getText().equals("Log In")){ //efoson to log_RegB exei text Log In o xristis thelei na kanei log in
                dispose();
                temp.logIn(userNameT.getText(), passwordT.getText());
            }else if(AdmorUsRadio().equals("A")){ //ama to log_RegB den exei text Log In o xristis thelei na kanei register os admin
                if(AdmCheck()){ //elenxei ama yparxei admin account
                    dispose();
                    temp.registerNewUser(userNameT.getText(), passwordT.getText(),passwordT1.getText(), AdmorUsRadio());
                }else{ //den uparxei admin account
                    JOptionPane.showMessageDialog(null, "There is no admins account with\nthat username or password.", 
                            "Security message", JOptionPane.PLAIN_MESSAGE);
                }
            }else{ //thelei na kanei register os user (toAdmorUsRadio exei epilegei to option gia register os user)
                dispose();
                temp.registerNewUser(userNameT.getText(), passwordT.getText(),passwordT1.getText(), AdmorUsRadio());
            }
        }
    }//GEN-LAST:event_log_RegBActionPerformed

    private void cancelTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelTActionPerformed
        GUI temp = new GUI(); //ama patisei o xristis cancel tote to programa ton epistrefei sto arxiko GUI
        temp.setLocationRelativeTo(null);
        temp.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelTActionPerformed

    private void quitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitBActionPerformed

    private void passwordTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTFocusGained
        if(passwordT.getText().equals("Enter your password.")){ // ama auto to field to kanei focus o xristis to text tha e3afanistei
            passwordT.setText("");
            passwordT.setEchoChar('*'); //oti grafei o xristis tha emfanizete se ***
        }
    }//GEN-LAST:event_passwordTFocusGained

    private void userNameTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTFocusGained
        if(userNameT.getText().equals("Enter your username.")){ 
            userNameT.setText("");
        }
    }//GEN-LAST:event_userNameTFocusGained

    private void userNameTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTFocusLost
        if(userNameT.getText().equals("")){ //ama xathei to focus apo to field kai den exei xrapsei tipota o xristis tote 
            userNameT.setText("Enter your username."); // grafete auto to text
        }
    }//GEN-LAST:event_userNameTFocusLost

    private void passwordTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTFocusLost
        if(passwordT.getText().equals("")){
            passwordT.setText("Enter your password.");
            passwordT.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_passwordTFocusLost

    private void passwordT1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordT1FocusGained
        if(passwordT1.getText().equals("Enter your password.")){
            passwordT1.setText("");
            passwordT1.setEchoChar('*');
        }
    }//GEN-LAST:event_passwordT1FocusGained

    private void passwordT1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordT1FocusLost
        if(passwordT1.getText().equals("")){
            passwordT1.setText("Enter your password.");
            passwordT1.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_passwordT1FocusLost

    private void adusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adusernameFocusGained
        if(adusername.getText().equals("Enter admins username.")){
            adusername.setText("");
        }
    }//GEN-LAST:event_adusernameFocusGained

    private void adusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adusernameFocusLost
        if(adusername.getText().equals("")){
            adusername.setText("Enter admins username.");
        }
    }//GEN-LAST:event_adusernameFocusLost

    private void adpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adpasswordFocusGained
       if(adpassword.getText().equals("Enter admins password.")){
            adpassword.setText("");
            adpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_adpasswordFocusGained

    private void adpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adpasswordFocusLost
        if(adpassword.getText().equals("")){
            adpassword.setText("Enter admins password.");
            adpassword.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_adpasswordFocusLost

    private void AdmRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmRadioActionPerformed
        jPanel2.setVisible(true); //ama patisei na kanei o xristis register os admin tote emfanizete to jPanel2
    }//GEN-LAST:event_AdmRadioActionPerformed

    private void UsRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsRadioActionPerformed
        jPanel2.setVisible(false); //ama patisei na kanei o xristis register os aplos user tote e3afanizete to jPanel2
    }//GEN-LAST:event_UsRadioActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         JOptionPane.showMessageDialog(null, "Enter your username and password. If you Register to the system as administrator, you must have an administrator's permission. ", 
                "Help Box",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private String AdmorUsRadio(){
        if (AdmRadio.isSelected()){ //admRadio exei epilegei
            return "A"; //o xristis thelei na kanei register os admin
        }else{ //UsRadio enabled
            return "U"; //o xristis thelei na kanei register os aplos user
        }        
    }
    
    
    private boolean AdmCheck(){ //ellegxei ama uparxei account tou admin pou edose permission ston neo xristi na kanei register os admin
        if(AdmorUsRadio().equals("A")){
            Admins admintemp = new Admins();
            return admintemp.adminChecker(adusername.getText(), adpassword.getText());
        }else{
            return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIforLogIn_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIforLogIn_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIforLogIn_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIforLogIn_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIforLogIn_Register('l').setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AdmRadio;
    private javax.swing.JMenu File;
    private javax.swing.JLabel UorAlabel;
    private javax.swing.JRadioButton UsRadio;
    private javax.swing.JPasswordField adpassword;
    private javax.swing.JTextField adusername;
    private javax.swing.JButton cancelT;
    private javax.swing.JLabel fieldsText;
    private javax.swing.JLabel fieldsText1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JButton log_RegB;
    private javax.swing.JLabel password;
    private javax.swing.JLabel password1;
    private javax.swing.JLabel password2;
    private javax.swing.JPasswordField passwordT;
    private javax.swing.JPasswordField passwordT1;
    private javax.swing.JMenuItem quitB;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel userName1;
    private javax.swing.JLabel userName2;
    private javax.swing.JLabel userName3;
    private javax.swing.JTextField userNameT;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
