/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2omeros;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 * This class is the interface that lets the user change his password
 * @author GeorgeKirm
 * @author GT
 */
public class GUIforChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form GUIforChangePassword
     */
    public GUIforChangePassword() {
        initComponents();
        pPasswordT.setEchoChar((char) 0); //to "password field" emdanizei to text se kanoniko alfabito kai oxi **
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nPassword2 = new javax.swing.JLabel();
        cancelB = new javax.swing.JButton();
        pPasswordT = new javax.swing.JPasswordField();
        nPassword1 = new javax.swing.JLabel();
        nPassword1T = new javax.swing.JTextField();
        nPassword2T = new javax.swing.JTextField();
        okB = new javax.swing.JButton();
        pPassword = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileB = new javax.swing.JMenu();
        quitB = new javax.swing.JMenuItem();
        helpB = new javax.swing.JMenu();
        help2B = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Password");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);

        nPassword2.setText("New password:");

        cancelB.setText("Cancel");
        cancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBActionPerformed(evt);
            }
        });

        pPasswordT.setText("Enter your password.");
        pPasswordT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pPasswordTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pPasswordTFocusLost(evt);
            }
        });

        nPassword1.setText("New password:");

        nPassword1T.setText("Enter new password.");
        nPassword1T.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nPassword1TFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nPassword1TFocusLost(evt);
            }
        });

        nPassword2T.setText("Enter it agien.");
        nPassword2T.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nPassword2TFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nPassword2TFocusLost(evt);
            }
        });

        okB.setText("Continue");
        okB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBActionPerformed(evt);
            }
        });

        pPassword.setText("Previous password:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okB)
                    .addComponent(pPassword)
                    .addComponent(nPassword1)
                    .addComponent(nPassword2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelB)
                    .addComponent(pPasswordT)
                    .addComponent(nPassword1T)
                    .addComponent(nPassword2T, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pPassword)
                    .addComponent(pPasswordT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nPassword1)
                    .addComponent(nPassword1T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nPassword2)
                    .addComponent(nPassword2T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okB)
                    .addComponent(cancelB))
                .addContainerGap())
        );

        fileB.setText("File");

        quitB.setText("Quit");
        quitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBActionPerformed(evt);
            }
        });
        fileB.add(quitB);

        jMenuBar1.add(fileB);

        helpB.setText("Help");

        help2B.setText("Help");
        help2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help2BActionPerformed(evt);
            }
        });
        helpB.add(help2B);

        jMenuBar1.add(helpB);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitBActionPerformed

    private void pPasswordTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pPasswordTFocusGained
        if(pPasswordT.getText().equals("Enter your password.")){ //otan kanei focus se auto to parathiro tha sbinete to text gia na grafei to password pou thelei o xristis
            pPasswordT.setText("");
            pPasswordT.setEchoChar('*');
        }
    }//GEN-LAST:event_pPasswordTFocusGained

    private void pPasswordTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pPasswordTFocusLost
        if(pPasswordT.getText().equals("")){ //otan xanete to focus apo auto to parathiro kai den egrapse tipota o xristis tha emfanizete to parakato minima
            pPasswordT.setText("Enter your password.");
            pPasswordT.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_pPasswordTFocusLost

    private void nPassword1TFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nPassword1TFocusGained
        if(nPassword1T.getText().equals("Enter new password.")){
            nPassword1T.setText("");
        }
    }//GEN-LAST:event_nPassword1TFocusGained

    private void nPassword1TFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nPassword1TFocusLost
        if(nPassword1T.getText().equals("")){
            nPassword1T.setText("Enter new password.");
        }
    }//GEN-LAST:event_nPassword1TFocusLost

    private void nPassword2TFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nPassword2TFocusGained
        if(nPassword2T.getText().equals("Enter it agien.")){
            nPassword2T.setText("");
        }
    }//GEN-LAST:event_nPassword2TFocusGained

    private void nPassword2TFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nPassword2TFocusLost
        if(nPassword2T.getText().equals("")){
            nPassword2T.setText("Enter it agien.");
        }
    }//GEN-LAST:event_nPassword2TFocusLost

    private void cancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBActionPerformed
        dispose();
    }//GEN-LAST:event_cancelBActionPerformed

    private void okBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBActionPerformed
        int n = JOptionPane.showConfirmDialog(null, "Are you sure you want to change your password?", 
                "Security Question", JOptionPane.YES_NO_OPTION); //minima gia to ama thelei o xristis na alla3ei ontos ton kodiko tou
        if (n == JOptionPane.YES_OPTION) {
            dispose(); 
            Users temp = new Users(); //kalei tin Users gia na alla3ei ton kodiko
            temp.changePassword(pPasswordT.getText(), nPassword1T.getText(), nPassword2T.getText());
        } else if (n == JOptionPane.NO_OPTION) {
            getContentPane().removeAll(); //ama pei oxi katharizonte ta kelia
            getContentPane().repaint();
            initComponents();
        }
    }//GEN-LAST:event_okBActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void help2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help2BActionPerformed
        JOptionPane.showMessageDialog(null, "You can change your password.\nConfirm your password"
                + "and enter a new valid password\n\n", 
                "Help Box",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_help2BActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIforChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIforChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIforChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIforChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIforChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelB;
    private javax.swing.JMenu fileB;
    private javax.swing.JMenuItem help2B;
    private javax.swing.JMenu helpB;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nPassword1;
    private javax.swing.JTextField nPassword1T;
    private javax.swing.JLabel nPassword2;
    private javax.swing.JTextField nPassword2T;
    private javax.swing.JButton okB;
    private javax.swing.JLabel pPassword;
    private javax.swing.JPasswordField pPasswordT;
    private javax.swing.JMenuItem quitB;
    // End of variables declaration//GEN-END:variables
}
