/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2omeros;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JToggleButton;
import javax.swing.JOptionPane;

/**
 * @author GeorgeKirm
 * @author GT
 */
public class GUIforHalls extends javax.swing.JFrame {

    /**
     * Creates new form GUIforHalls
     */
    public GUIforHalls() {
        
    }
    
    public GUIforHalls(boolean itIsCinema) {
        initComponents();
        horizonticallyTshow.setEnabled(false);
        verticallyTshow.setEnabled(false);
        balconiesTshow.setEnabled(false);
        dressingRoomsTshow.setEnabled(false);
        displayDressingTshow.setEditable(false);
        soundBalconiesTshow.setEditable(false);
        hallNameTshow.setEditable(false);
        eventNameTShow.setText("Editing all Halls");
        editSaveB.setEnabled(false);
        bookSeatsB.setEnabled(false);
        addAsNewHallB.setEnabled(false);
        cancel2B.setEnabled(false);
        cancel2B.setVisible(false);
        deleteHallB.setEnabled(false);
        HallSeats temp = new HallSeats();
        if(itIsCinema){
            editHallP.remove(balconiesT);
            editHallP.remove(balconiesTshow);
            editHallP.remove(dressingRoomsT);
            editHallP.remove(dressingRoomsTshow);
            eventNameT.setText("Cinema halls");
            List<String> namesOfMovies = temp.getCinemaHalls();
            for (String s : namesOfMovies) {
                hallsL.addItem(s);
            }
            editAllCinemaB.setEnabled(false);
        }else{
            remove(cinemaTheaterInfoP);
            eventNameT.setText("theater halls");
            List<String> namesOfPerformances = temp.getTheaterHalls();
            for (String s : namesOfPerformances) {
                hallsL.addItem(s);
            }
            editAllTheaterB.setEnabled(false);
        }
        
        if(hallsL.getItemCount()==0){
            hallsL.addItem("No halls");
        }
        revalidate();
        repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editSaveB = new javax.swing.JButton();
        eventNameTShow = new javax.swing.JLabel();
        cinemaTheaterInfoP = new javax.swing.JPanel();
        displayDressingT = new javax.swing.JLabel();
        displayDressingTshow = new javax.swing.JTextField();
        soundBalconiesT = new javax.swing.JLabel();
        soundBalconiesTshow = new javax.swing.JTextField();
        cancelB = new javax.swing.JButton();
        hallsT = new javax.swing.JLabel();
        showHallB = new javax.swing.JButton();
        deleteHallB = new javax.swing.JButton();
        eventNameT = new javax.swing.JLabel();
        editAllTheaterB = new javax.swing.JButton();
        addAsNewHallB = new javax.swing.JCheckBox();
        hallsL = new javax.swing.JComboBox();
        editHallP = new javax.swing.JPanel();
        hallNameT = new javax.swing.JLabel();
        hallNameTshow = new javax.swing.JTextField();
        enterSeatsT = new javax.swing.JLabel();
        horizonticallyT = new javax.swing.JLabel();
        verticallyT = new javax.swing.JLabel();
        balconiesT = new javax.swing.JLabel();
        dressingRoomsT = new javax.swing.JLabel();
        verticallyTshow = new javax.swing.JSpinner();
        horizonticallyTshow = new javax.swing.JSpinner();
        balconiesTshow = new javax.swing.JSpinner();
        dressingRoomsTshow = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        cancel2B = new javax.swing.JButton();
        bookSeatsB = new javax.swing.JButton();
        editAllCinemaB = new javax.swing.JButton();
        sheatsP = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        changePassword = new javax.swing.JMenuItem();
        deleteAccount = new javax.swing.JMenuItem();
        logOut = new javax.swing.JMenuItem();
        quit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editSaveB.setText("Edit hall");
        editSaveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSaveBActionPerformed(evt);
            }
        });

        eventNameTShow.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        eventNameTShow.setText("hello ladies");

        cinemaTheaterInfoP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 125, 189)));
        cinemaTheaterInfoP.setForeground(new java.awt.Color(62, 125, 189));

        displayDressingT.setText("Display system");

        displayDressingTshow.setText("-");

        soundBalconiesT.setText("Sound system");

        soundBalconiesTshow.setText("-");

        javax.swing.GroupLayout cinemaTheaterInfoPLayout = new javax.swing.GroupLayout(cinemaTheaterInfoP);
        cinemaTheaterInfoP.setLayout(cinemaTheaterInfoPLayout);
        cinemaTheaterInfoPLayout.setHorizontalGroup(
            cinemaTheaterInfoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cinemaTheaterInfoPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cinemaTheaterInfoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayDressingT)
                    .addComponent(soundBalconiesT))
                .addGap(43, 43, 43)
                .addGroup(cinemaTheaterInfoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soundBalconiesTshow, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayDressingTshow, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        cinemaTheaterInfoPLayout.setVerticalGroup(
            cinemaTheaterInfoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cinemaTheaterInfoPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cinemaTheaterInfoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayDressingT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayDressingTshow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cinemaTheaterInfoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soundBalconiesT)
                    .addComponent(soundBalconiesTshow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        cancelB.setText("Return to events panel");
        cancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBActionPerformed(evt);
            }
        });

        hallsT.setText("List of halls:");

        showHallB.setText("Show Hall");
        showHallB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHallBActionPerformed(evt);
            }
        });

        deleteHallB.setText("Delete Hall");
        deleteHallB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteHallBActionPerformed(evt);
            }
        });

        eventNameT.setText("Event name:");

        editAllTheaterB.setText("Edit all theater halls");
        editAllTheaterB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAllTheaterBActionPerformed(evt);
            }
        });

        addAsNewHallB.setText("add new hall");
        addAsNewHallB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAsNewHallBActionPerformed(evt);
            }
        });

        editHallP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 125, 189)));

        hallNameT.setText("The selected hall is:");

        hallNameTshow.setText("-");

        enterSeatsT.setText("Please enter the number of");

        horizonticallyT.setText("seats horizontically");

        verticallyT.setText("seats vertically");

        balconiesT.setText("balconies");

        dressingRoomsT.setText("dressing rooms");

        verticallyTshow.setModel(new javax.swing.SpinnerNumberModel(22, 1, 22, 1));

        horizonticallyTshow.setModel(new javax.swing.SpinnerNumberModel(37, 1, 37, 1));

        balconiesTshow.setModel(new javax.swing.SpinnerNumberModel(99, 1, 99, 1));

        dressingRoomsTshow.setModel(new javax.swing.SpinnerNumberModel(99, 1, 99, 1));

        jLabel1.setText("Time");

        jTextField1.setText("jTextField1");

        cancel2B.setText("cancel");
        cancel2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel2BActionPerformed(evt);
            }
        });

        bookSeatsB.setText("See sheats");
        bookSeatsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookSeatsBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editHallPLayout = new javax.swing.GroupLayout(editHallP);
        editHallP.setLayout(editHallPLayout);
        editHallPLayout.setHorizontalGroup(
            editHallPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editHallPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editHallPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hallNameTshow, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterSeatsT)
                    .addComponent(hallNameT)
                    .addGroup(editHallPLayout.createSequentialGroup()
                        .addGroup(editHallPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(horizonticallyT)
                            .addComponent(verticallyT)
                            .addComponent(balconiesT)
                            .addComponent(dressingRoomsT)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editHallPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dressingRoomsTshow)
                            .addComponent(balconiesTshow)
                            .addComponent(verticallyTshow)
                            .addComponent(horizonticallyTshow)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(editHallPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bookSeatsB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancel2B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(77, 77, 77))
        );
        editHallPLayout.setVerticalGroup(
            editHallPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editHallPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(editHallPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editHallPLayout.createSequentialGroup()
                        .addGroup(editHallPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hallNameT)
                            .addComponent(cancel2B))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hallNameTshow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enterSeatsT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editHallPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(horizonticallyT)
                            .addComponent(horizonticallyTshow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editHallPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(verticallyT)
                            .addComponent(verticallyTshow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editHallPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(balconiesT)
                            .addComponent(balconiesTshow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editHallPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dressingRoomsT)
                            .addComponent(dressingRoomsTshow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editHallPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(editHallPLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(bookSeatsB))))
        );

        editAllCinemaB.setText("Edit all cinema halls");
        editAllCinemaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAllCinemaBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(eventNameT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eventNameTShow, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editHallP, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(showHallB)
                                    .addComponent(hallsT, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(editSaveB, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addAsNewHallB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(deleteHallB))
                                    .addComponent(hallsL, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cinemaTheaterInfoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cancelB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(editAllCinemaB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(editAllTheaterB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventNameT)
                    .addComponent(eventNameTShow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hallsT)
                    .addComponent(hallsL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showHallB)
                    .addComponent(editSaveB)
                    .addComponent(addAsNewHallB)
                    .addComponent(deleteHallB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editHallP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cinemaTheaterInfoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editAllCinemaB)
                    .addComponent(editAllTheaterB))
                .addContainerGap())
        );

        sheatsP.setBackground(new java.awt.Color(254, 254, 254));
        sheatsP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        sheatsP.setForeground(new java.awt.Color(255, 0, 0));
        sheatsP.setMaximumSize(new java.awt.Dimension(815, 499));
        sheatsP.setMinimumSize(new java.awt.Dimension(815, 499));

        javax.swing.GroupLayout sheatsPLayout = new javax.swing.GroupLayout(sheatsP);
        sheatsP.setLayout(sheatsPLayout);
        sheatsPLayout.setHorizontalGroup(
            sheatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
        );
        sheatsPLayout.setVerticalGroup(
            sheatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        changePassword.setText("Change password");
        changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordActionPerformed(evt);
            }
        });
        jMenu1.add(changePassword);

        deleteAccount.setText("Delete account");
        deleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountActionPerformed(evt);
            }
        });
        jMenu1.add(deleteAccount);

        logOut.setText("Log out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        jMenu1.add(logOut);

        quit.setText("Quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        jMenu1.add(quit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem1.setText("Help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sheatsP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sheatsP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBActionPerformed
        dispose();
        GUIforUser temp = new GUIforUser();
        temp.setLocationRelativeTo(null);
        temp.setVisible(true);
    }//GEN-LAST:event_cancelBActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    private void changePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordActionPerformed
        GUIforChangePassword temp1 = new GUIforChangePassword();
        temp1.setLocationRelativeTo(null);
        temp1.setVisible(true);
    }//GEN-LAST:event_changePasswordActionPerformed

    private void deleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountActionPerformed
        int n = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete your account?", 
                "Security Question", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            Users temp1 = new Users();
            dispose();
            temp1.deleteAccount();
            GUI temp2 = new GUI();
            temp2.setLocationRelativeTo(null);
            temp2.setVisible(true);
        } else if (n == JOptionPane.NO_OPTION) {

        } else {
        }
    }//GEN-LAST:event_deleteAccountActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        dispose();
        Users temp1 = new Users();
        temp1.logOut();
        GUI temp2 = new GUI();
        temp2.setLocationRelativeTo(null);
        temp2.setVisible(true);
    }//GEN-LAST:event_logOutActionPerformed

    private void showHallBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHallBActionPerformed
        editSaveB.setEnabled(true);
        bookSeatsB.setEnabled(true);
        HallSeats temp = new HallSeats();
        List<String> info;
        if(eventNameT.getText().equals("Cinema halls")){
            if(hallsL.getSelectedItem().equals("No halls")){
                addAsNewHallB.doClick();
                hallNameTshow.setText("There is no hall for that movie");
                displayDressingTshow.setText("-");
                soundBalconiesTshow.setText("-");
                horizonticallyTshow.setValue(99);
                verticallyTshow.setValue(99);
            }else{
                deleteHallB.setEnabled(true);
                String nameOfHall = hallsL.getSelectedItem().toString();
                info = temp.showHall(nameOfHall, true);
                hallNameTshow.setText(nameOfHall);
                displayDressingTshow.setText(info.get(1));
                soundBalconiesTshow.setText(info.get(2));
                horizonticallyTshow.setValue(Integer.parseInt(info.get(3)));
                verticallyTshow.setValue(Integer.parseInt(info.get(4)));
            }
        }else if(eventNameT.getText().equals("theater halls")){
            if(hallsL.getSelectedItem().equals("No halls")){
                addAsNewHallB.doClick();
                hallNameTshow.setText("There is no hall for that performance");
                balconiesTshow.setValue(99);
                dressingRoomsTshow.setValue(99);
                horizonticallyTshow.setValue(99);
                verticallyTshow.setValue(99);
            }else{
                deleteHallB.setEnabled(true);
                String nameOfHall = hallsL.getSelectedItem().toString();
                info = temp.showHall(nameOfHall,false);
                hallNameTshow.setText(nameOfHall);
                balconiesTshow.setValue(Integer.parseInt(info.get(1)));
                dressingRoomsTshow.setValue(Integer.parseInt(info.get(2)));
                horizonticallyTshow.setValue(Integer.parseInt(info.get(3)));
                verticallyTshow.setValue(Integer.parseInt(info.get(4)));
            }
        }
    }//GEN-LAST:event_showHallBActionPerformed

    private void editSaveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSaveBActionPerformed
        if(editSaveB.getText().equals("Save hall")){
            if(true){
                //ftiaxnei ta koumpia sto interface
                List<String> info = new ArrayList<String>();
                String hallNameChecker = hallNameTshow.getText();
                if(addAsNewHallB.isSelected()){ // elegxei ama o xristeis thelei na kanei add to event
                    addAsNewHallB.doClick(); //3etsekarei
                    if(hallsL.getSelectedItem().equals("No halls")){
                        if(eventNameT.getText().equals("Cinema halls")){
                            hallsL.removeAllItems(); //Ama thelei na kanei kai to jcompobox den exei teneies tote bgazei to boithitiko event
                        }else{
                            int i=0;
                            while(i<hallsL.getItemCount()){
                                if(hallNameChecker.equals(hallsL.getSelectedItem())){
                                    hallNameChecker= hallNameTshow.getText()+"Copy";
                                    i=-1;
                                }
                                i++;
                            }
                        }
                    }else{
                        if(eventNameT.getText().equals("Cinema halls")){
                            hallsL.removeAllItems();
                        }else{                 
                            int i=0;
                            while(i<hallsL.getItemCount()){
                                if(hallNameChecker.equals(hallsL.getSelectedItem())){
                                    hallNameChecker= hallNameTshow.getText()+"Copy";
                                    i=-1;
                                }
                                i++;
                            }
                        }           
                    }
                }
                if(eventNameT.getText().equals("Cinema halls")){
                    info.add("C");
                    info.add(displayDressingTshow.getText());
                    info.add(soundBalconiesTshow.getText());
                }else{
                    info.add("T");
                    info.add(balconiesTshow.getValue().toString());
                    info.add(dressingRoomsTshow.getValue().toString());
                }
                info.add(horizonticallyTshow.getValue().toString());
                info.add(verticallyTshow.getValue().toString());
                HallSeats temp = new HallSeats();
                temp.editHalls(hallNameChecker, info, eventNameT.getText().equals("Cinema halls"));
//                dispose();
                GUIforHalls temp1 = new GUIforHalls(eventNameT.getText().equals("Cinema halls"));
                temp1.setLocationRelativeTo(null);
                temp1.setVisible(true);
            }else{
                if(hallNameTshow.getText().equals("No halls")){
                    JOptionPane.showMessageDialog(null, "Please put a real name for the hall.",
                            "Error message", JOptionPane.PLAIN_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(null, "Please dont use this character sequance "
                            + "\">~~Dnt@Dlt~~<\".", "Error message", JOptionPane.PLAIN_MESSAGE);
                }
            }
        }else if(editSaveB.getText().equals("Edit hall")){ //o xristis patise to koumpi gia na kanei edit to event
            deleteHallB.setEnabled(false);
            hallsL.setEnabled(false);
            editSaveB.setText("Save hall");
            horizonticallyTshow.setEnabled(true);
            verticallyTshow.setEnabled(true);
            balconiesTshow.setEnabled(true);
            dressingRoomsTshow.setEnabled(true);
            addAsNewHallB.setEnabled(true);
            cancel2B.setEnabled(true);
            cancel2B.setVisible(true);
            displayDressingTshow.setEditable(true);
            soundBalconiesTshow.setEditable(true);
            addAsNewHallB.setEnabled(true);
            addAsNewHallBActionPerformed(evt);
            showHallB.setEnabled(false);
            bookSeatsB.setEnabled(false);
            sheatsP.removeAll();
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_editSaveBActionPerformed

    private void addAsNewHallBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAsNewHallBActionPerformed
        if(!addAsNewHallB.isSelected()){
            hallNameTshow.setEditable(false);
            if(hallsL.getSelectedItem().equals("No halls")){
                if(editSaveB.getText().equals("Save Event")){
                    addAsNewHallB.doClick();
                }
            }
        }else{
            hallNameTshow.setEditable(true);
        }
    }//GEN-LAST:event_addAsNewHallBActionPerformed

    private void editAllCinemaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAllCinemaBActionPerformed
//        dispose();
        GUIforHalls temp = new GUIforHalls(true);
        temp.setLocationRelativeTo(null);
        temp.setVisible(true);
    }//GEN-LAST:event_editAllCinemaBActionPerformed

    private void editAllTheaterBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAllTheaterBActionPerformed
//        dispose();
        GUIforHalls temp = new GUIforHalls(false);
        temp.setLocationRelativeTo(null);
        temp.setVisible(true);
    }//GEN-LAST:event_editAllTheaterBActionPerformed

    private void cancel2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel2BActionPerformed
//        dispose();
        GUIforHalls temp = new GUIforHalls(eventNameT.getText().equals("Cinema halls"));
        temp.setLocationRelativeTo(null);
        temp.setVisible(true);
    }//GEN-LAST:event_cancel2BActionPerformed

    private void deleteHallBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteHallBActionPerformed
        int n = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this event?", 
                "Security Question", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            HallSeats temp = new HallSeats();
            String nameOfEvent;
            int numberI = hallsL.getSelectedIndex();
            nameOfEvent = hallsL.getSelectedItem().toString();
            if(eventNameT.getText().equals("Cinema halls")){
                temp.deleteHall(nameOfEvent, true);
            }else{
                temp.deleteHall(nameOfEvent, false);
            }
            hallsL.removeItemAt(numberI);
            if(hallsL.getItemCount()==0){
                hallsL.addItem("No halls");
            }
        } else if (n == JOptionPane.NO_OPTION) {

        }
    }//GEN-LAST:event_deleteHallBActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(null, "Not many things are working here", 
                "Help Box",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void bookSeatsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookSeatsBActionPerformed
        loula();
    }//GEN-LAST:event_bookSeatsBActionPerformed
    
    private void loula(){
        int q1 = Integer.parseInt(horizonticallyTshow.getValue().toString());
        int q2 = Integer.parseInt(verticallyTshow.getValue().toString());
        sheatsP.setLayout(new GridLayout(q2, q1, 2, 2)); 
        //sheatsP.setLayout(new GridBagLayout()); 
        Dimension d = new Dimension(20, 20);
        for (int i = 1; i<=q1 ;i++) {  
             for (int j = 1; j<=q2 ;j++) {  
                JToggleButton button = new JToggleButton("");  
                sheatsP.add(button); 
                button.setSize(20, 20);
                button.setMinimumSize(d);
                button.setMaximumSize(d);
                button.setLocation(21*i, 21*j);
             }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIforHalls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIforHalls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIforHalls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIforHalls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIforHalls().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox addAsNewHallB;
    private javax.swing.JLabel balconiesT;
    private javax.swing.JSpinner balconiesTshow;
    private javax.swing.JButton bookSeatsB;
    private javax.swing.JButton cancel2B;
    private javax.swing.JButton cancelB;
    private javax.swing.JMenuItem changePassword;
    private javax.swing.JPanel cinemaTheaterInfoP;
    private javax.swing.JMenuItem deleteAccount;
    private javax.swing.JButton deleteHallB;
    private javax.swing.JLabel displayDressingT;
    private javax.swing.JTextField displayDressingTshow;
    private javax.swing.JLabel dressingRoomsT;
    private javax.swing.JSpinner dressingRoomsTshow;
    private javax.swing.JButton editAllCinemaB;
    private javax.swing.JButton editAllTheaterB;
    private javax.swing.JPanel editHallP;
    private javax.swing.JButton editSaveB;
    private javax.swing.JLabel enterSeatsT;
    private javax.swing.JLabel eventNameT;
    private javax.swing.JLabel eventNameTShow;
    private javax.swing.JLabel hallNameT;
    private javax.swing.JTextField hallNameTshow;
    private javax.swing.JComboBox hallsL;
    private javax.swing.JLabel hallsT;
    private javax.swing.JLabel horizonticallyT;
    private javax.swing.JSpinner horizonticallyTshow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem logOut;
    private javax.swing.JMenuItem quit;
    private javax.swing.JPanel sheatsP;
    private javax.swing.JButton showHallB;
    private javax.swing.JLabel soundBalconiesT;
    private javax.swing.JTextField soundBalconiesTshow;
    private javax.swing.JLabel verticallyT;
    private javax.swing.JSpinner verticallyTshow;
    // End of variables declaration//GEN-END:variables
}
